[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class float-term"
class = "float-term"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.notes]
animation = "fromRight"
command = "gnome-text-editor --new-window"
class = "org.gnome.TextEditor"
size = "41% 94%"
max_size = "1920px 100%"
unfocus = "hide"
position = "58% 5%"
